import fs from 'fs';

const qb = JSON.parse(fs.readFileSync('./src/data/questions.json', 'utf8'));

const newU18 = [];

// Add 5 more U18 TF (total 7)
const u18TF_more = [
  { id: "u18tf3", cat: "Advanced Tactics", pos: ["F","D"], concept: "High-risk high-reward", sit: "In a playoff game tied in overtime, taking a high-risk pass through the middle to create a chance is justified if it could lead to a goal.", ok: true, why: "In overtime playoff, risk-reward favors creating scoring chances. One mistake ends the game, but so does playing safe.", tip: "OT hockey: controlled risk for chances." },
  { id: "u18tf4", cat: "Leadership", pos: ["F","D"], concept: "Holding players accountable", sit: "Only the team captain should hold teammates accountable because it's a position of authority.", ok: false, why: "Any player can hold others accountable through their actions, words, and attitude. Leadership is earned through effort, not title.", tip: "Leadership is action, not title." },
  { id: "u18tf5", cat: "Neutral Zone Play", pos: ["D"], concept: "Stretch pass", sit: "Using a stretch pass in neutral zone is always risky and should be avoided in favor of shorter, safer options.", ok: false, why: "Stretch passes, when executed properly with support, are high-percentage transition tools. Risk depends on read and execution.", tip: "Stretch pass: read, execute, support." },
  { id: "u18tf6", cat: "Game Management", pos: ["F","D"], concept: "Protecting late lead", sit: "When up 4-2 with 5 minutes left, you should focus on not making mistakes rather than creating new chances.", ok: true, why: "Late lead protection is about controlled possession and smart decisions, not offensive creation.", tip: "Late lead: control possession." },
  { id: "u18tf7", cat: "Breakout Execution", pos: ["D"], concept: "D handling puck", sit: "In the modern game, defensemen should pass the puck immediately rather than handle it because the pressure is too intense.", ok: false, why: "Skilled D create advantages by handling the puck and changing angles. This is a critical modern skill at high levels.", tip: "Modern D: handle, create, pass." }
];

// Add 5 more U18 Seq (total 6)
const u18Seq_more = [
  { id: "u18seq2", cat: "Advanced Tactics", pos: ["F","D"], concept: "Forecheck aggressiveness", sit: "Order the steps of deciding how aggressive to forecheck based on game situation.", items: ["Assess game score and time remaining", "Determine risk-reward of aggressive forecheck", "Adjust pressure intensity accordingly", "Be ready to transition if forecheck fails"], correct_order: [0,1,2,3], why: "Forecheck intensity depends on game situation. Up 3-1? Conservative. Down 0-1? Aggressive.", tip: "Forecheck: situational intensity." },
  { id: "u18seq3", cat: "Game Management", pos: ["F","D"], concept: "Late-game execution", sit: "Order the priorities for managing the final 2 minutes of a game up by 1.", items: ["Control the puck in your zone", "Make crisp passes to clear zone", "Avoid giving opponent scoring chances", "Run time off clock with possession"], correct_order: [0,1,2,3], why: "Final minutes require possession control and smart clearing to run time.", tip: "Final minutes: possession, clear, run time." },
  { id: "u18seq4", cat: "Neutral Zone Play", pos: ["F","D"], concept: "Transition read sequence", sit: "Order the steps of reading a neutral zone transition situation.", items: ["Identify numerical advantage or disadvantage", "Read defenseman positioning and depth", "Decide entry strategy (carry, chip, pass)", "Execute with support timing"], correct_order: [0,1,2,3], why: "Transition reads require first assessing numbers, then D positioning, then choosing entry.", tip: "Transition read: numbers, D depth, entry choice." },
  { id: "u18seq5", cat: "Leadership", pos: ["F","D"], concept: "Building team momentum", sit: "Order the steps of building momentum after a negative play or mistake.", items: ["Acknowledge the mistake without dwelling on it", "Make the next positive play with intensity", "Communicate confidence to teammates", "Build on the play with continued effort"], correct_order: [0,1,2,3], why: "Momentum recovery requires acknowledgment, immediate positive action, communication, and sustained effort.", tip: "Momentum: reset, attack, talk, sustain." },
  { id: "u18seq6", cat: "Advanced Tactics", pos: ["D"], concept: "Pinch decision sequence", sit: "Order the steps of deciding whether to pinch as the O-zone D.", items: ["Assess puck position and rim direction", "Check if your partner has back coverage", "Evaluate whether you can win the puck", "Commit to the pinch or hold the line"], correct_order: [0,1,2,3], why: "Pinch decisions require puck awareness, partner support coverage, win probability, then commitment.", tip: "Pinch: puck, coverage, win %, commit." }
];

// Add 7 more U18 Mistake (total 8)
const u18Mistake_more = [
  { id: "u18mis2", cat: "Leadership", pos: ["F","D"], concept: "Blame culture", sit: "After a goal against, you blame your defenseman publicly instead of discussing it privately after the game. What's the mistake?", opts: ["You should have prevented the goal yourself.", "Public blame erodes team culture — address mistakes privately and move forward together.", "You should have kept it to yourself.", "The defenseman made the mistake, so it's their fault."], ok: 1, why: "Great teams address mistakes privately and move forward. Public blame creates division.", tip: "Mistakes: address privately, move forward." },
  { id: "u18mis3", cat: "Game Management", pos: ["F","D"], concept: "Emotional play", sit: "After a controversial call against you, you retaliate with an obvious penalty. What's the mistake?", opts: ["You were justified.", "You let emotion override judgment — responding to the ref's call gives them the final say.", "The call was wrong.", "You should have hit them harder."], ok: 1, why: "Great players channel emotion into good play, not retaliation. Emotional play = penalties.", tip: "Channel emotion into smart play." },
  { id: "u18mis4", cat: "Advanced Tactics", pos: ["D"], concept: "Over-aggressive pinch", sit: "With your partner still in defensive zone coverage behind the net, you pinch aggressively on the wing. Rim-out breaks behind you. What's the mistake?", opts: ["You should have stayed home.", "You pinched without confirming partner coverage — break goes behind you for odd-man rush.", "Your partner should have helped.", "The play was too fast."], ok: 1, why: "Pinching requires confirmed back coverage. Without it, you create breakaways.", tip: "Pinch: confirm back coverage first." },
  { id: "u18mis5", cat: "Neutral Zone Play", pos: ["F"], concept: "Neutral zone turnover", sit: "In neutral zone with the puck, you try a showboat deke against pressure and lose the puck. Immediate odd-man against you. What's the mistake?", opts: ["You should have tried harder.", "You took an unnecessary risk in a high-risk area — possession matters in neutral zone.", "The defender was lucky.", "You should have passed earlier."], ok: 1, why: "Neutral zone turnovers create odd-man against you. Smart play > style points.", tip: "Neutral zone: possession over style." },
  { id: "u18mis6", cat: "Breakout Execution", pos: ["D"], concept: "Poor breakout decision", sit: "Facing aggressive forecheck, you try to stickhandle through traffic instead of making a quick first pass. You're turned over deep. What's the mistake?", opts: ["You were too fancy.", "You held puck too long under heavy forecheck — quick first pass beats pressure.", "The forecheck was too good.", "You should have dumped it."], ok: 1, why: "Under forecheck, quick decision and pass beats fancy handling.", tip: "Heavy forecheck: quick pass." },
  { id: "u18mis7", cat: "Special Teams", pos: ["F","D"], concept: "PP execution failure", sit: "On power play with man advantage, you pass the puck 5 times without taking a shot, and the PK kills it. What's the mistake?", opts: ["You should have shot immediately.", "You overplayed — man advantage is for scoring, not just passing. Take high-percentage shots.", "The PK was good.", "Someone should have scored."], ok: 1, why: "Power play success requires shot volume. Passing only kills time.", tip: "Power play: take shots, create chances." },
  { id: "u18mis8", cat: "Game Management", pos: ["F","D"], concept: "Selfish play under pressure", sit: "Down 3-2 with 2 minutes left, instead of trusting your linemates to create chances, you try to deke through three defenders. Turnover ends the game. What's the mistake?", opts: ["You should have passed earlier.", "You became selfish under pressure — trust your teammates and make smart plays.", "Your linemates weren't in position.", "You tried too hard."], ok: 1, why: "Pressure situations require trust in teammates and smart play, not individual heroics.", tip: "Late pressure: trust, execute, support." }
];

// Add 5 more U18 Next (total 6)
const u18Next_more = [
  { id: "u18next2", cat: "Game Management", pos: ["F","D"], concept: "Momentum swing", sit: "You score to tie the game 2-2 in the third period. The other team immediately calls timeout. What happens next?", opts: ["You celebrate aggressively.", "You stay focused and aggressive — momentum is yours, don't let timeout reset it.", "You defend and be conservative.", "You prepare for overtime."], ok: 1, why: "After scoring to tie, maintain aggressive play. Timeout is opponent's reset, not yours.", tip: "Keep momentum: stay aggressive after scoring." },
  { id: "u18next3", cat: "Leadership", pos: ["F","D"], concept: "Team response to adversity", sit: "Your team gives up two goals in 30 seconds. As a leader, what happens next?", opts: ["Stay silent and let emotions settle.", "Call teammates together, reset focus, and demand immediate response with intensity.", "Request to sit out.", "Wait for coach to address it."], ok: 1, why: "Leaders respond immediately to adversity and call team to action. Silence enables panic.", tip: "Adversity: leaders call reset." },
  { id: "u18next4", cat: "Advanced Tactics", pos: ["D"], concept: "High-risk play reward", sit: "You complete a difficult transition pass that creates a 2-on-1 breakaway. What happens next?", opts: ["Play defensively to cover risk you took.", "Stay up ice and support the play — you earned the aggressive position with a good read.", "Back off and regroup.", "Head to bench to rest."], ok: 1, why: "Good high-risk plays earn the right to support the opportunity. Stay engaged.", tip: "Good risk: stay involved and support." },
  { id: "u18next5", cat: "Neutral Zone Play", pos: ["F"], concept: "Numerical advantage transition", sit: "You gain possession in neutral zone and realize you have a 3-on-2 advantage. What next?", opts: ["Slow down and set up.", "Push with speed immediately — 3-on-2 goes downhill fast if you attack with pace.", "Wait for support.", "Make a safe pass."], ok: 1, why: "3-on-2 advantages diminish with time. Push with speed immediately.", tip: "Numerical advantage: attack with speed." },
  { id: "u18next6", cat: "Breakout Execution", pos: ["D"], concept: "Breakout success transition", sit: "You complete a clean breakout and your forwards have a 2-on-1 rush. What next?", opts: ["Return to defense immediately.", "Push up ice in support of the rush — if play comes back, you're in position.", "Stay deep in zone.", "Change immediately."], ok: 1, why: "After a clean breakout supporting the rush keeps pressure and prevents backhand entries.", tip: "Breakout success: support the rush." }
];

for (const q of u18TF_more) newU18.push({...q, d: 3, type: "tf", source: "Hockey Canada — Midget Program / NCCP Advanced Coaching"});
for (const q of u18Seq_more) newU18.push({...q, d: 3, type: "seq", source: "Hockey Canada — Midget Program / NCCP Advanced Coaching"});
for (const q of u18Mistake_more) newU18.push({...q, d: 3, type: "mistake", source: "Hockey Canada — Midget Program / NCCP Advanced Coaching"});
for (const q of u18Next_more) newU18.push({...q, d: 3, type: "next", source: "Hockey Canada — Midget Program / NCCP Advanced Coaching"});

qb["U18 / Midget"].push(...newU18);

fs.writeFileSync('./src/data/questions.json', JSON.stringify(qb));
console.log(`✓ Expanded U18 with ${newU18.length} new questions`);
console.log(`U18 now has ${qb["U18 / Midget"].length} total questions`);
console.log(`\nPhase 5 Complete: Added 55 questions total`);
console.log(`  U15: 30 questions (TF: 7, Seq: 8, Mistake: 8, Next: 7)`);
console.log(`  U18: 25 questions (TF: 7, Seq: 6, Mistake: 8, Next: 6)`);
