import { practiceStorageKey, readPracticeValue } from './practiceStorage.js';
import { useCallback, useEffect, useRef, useState } from 'react';
import PracticeScene from './PracticeScene.jsx';
import { createDraft, addActor, removeActor, putKey, setFrozen, sampleDraft, validateDraft } from './director.js';
import { createTeamGame, stepTeamGame } from './teamSimulation.js';
import { feetPointToRinkFrame } from '../scenario-engine/rinkFrame.js';

function assertDraft(draft){const check=validateDraft(draft);if(!check.ok)throw new Error(check.errs.join('; '));return draft;}
export function draftFromPlay(play) {
  if(play.space?.units!=='rink-200x85') throw new Error('This source needs a coordinate adapter before it can be edited.');
  const node=play.nodes[play.start];
  const actors=play.actors.filter(a=>(node.enter?.[a.id]||node.pos?.[a.id])).map(a=>{
    const from=feetPointToRinkFrame(node.enter?.[a.id]||node.pos[a.id]),to=feetPointToRinkFrame(node.pos?.[a.id]||node.enter[a.id]);
    const facing=Math.atan2(to[1]-from[1],to[0]-from[0]);
    return {id:a.id,label:a.label||a.id,team:a.team,role:a.role==='goalie'?'goalie':'skater',frozen:false,fixedPose:null,keys:[{time:0,x:from[0],y:from[1],facing},{time:1.4,x:to[0],y:to[1],facing}]};
  });
  const draft={...createDraft(1,1),title:`${play.title} · exploration`,actors,puck:{owner:play.actors.find(a=>a.role==='puckCarrier')?.id||null},sourceRef:{id:play.id,nodeId:play.start,note:play.sourceRef?.note},status:'development-not-validated'};
  assertDraft(draft);return draft;
}
function downloadDraft(draft){assertDraft(draft);const url=URL.createObjectURL(new Blob([JSON.stringify(draft,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='rinkreads-coach-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function CoachLab({sourcePlay,initialDraft,onDraftChange,onCreateQuestion,playerId='practice-preview'}) {
  const saveKey=practiceStorageKey('rinkreads_director_library_v1',playerId);
  const [draft,setDraft]=useState(()=>initialDraft||(sourcePlay?draftFromPlay(sourcePlay):createDraft(2,2)));
  const draftRef=useRef(draft),timeRef=useRef(0),frameRef=useRef(sampleDraft(draft,0));
  const axesRef=useRef('horizontal');
  const [time,setTime]=useState(0),[frame,setFrame]=useState(frameRef.current),[selected,setSelected]=useState(draft.actors[0].id);
  const [camera,setCamera]=useState('full'),[running,setRunning]=useState(false),[live,setLive]=useState(false),[notice,setNotice]=useState(''),[speed,setSpeed]=useState(1),[saved,setSaved]=useState([]);
  const runRef=useRef(false),liveRef=useRef(false),speedRef=useRef(1),cameraRef=useRef('full'),keys=useRef(new Set()),action=useRef(null),stick=useRef({x:0,y:0});
  const stop=useCallback(()=>{runRef.current=false;setRunning(false);keys.current.clear();stick.current={x:0,y:0};action.current=null;},[]);
  function show(t,next=draftRef.current){timeRef.current=t;setTime(t);const f=sampleDraft(next,t);frameRef.current=f;setFrame(f);}
  function edit(fn){stop();liveRef.current=false;setLive(false);try{const next=fn(draftRef.current);assertDraft(next);draftRef.current=next;setDraft(next);onDraftChange?.(next);show(timeRef.current,next);setNotice('');}catch(e){setNotice(e.message)}}
  function replace(next){stop();assertDraft(next);draftRef.current=next;setDraft(next);onDraftChange?.(next);liveRef.current=false;setLive(false);setSelected(next.actors[0].id);show(0,next);}
  useEffect(()=>{
    let id,last=0,acc=0,painted=0;
    function tick(now){id=requestAnimationFrame(tick);const dt=last?Math.min(.1,(now-last)/1000):0;last=now;if(!runRef.current){acc=0;return;}
      if(liveRef.current){acc=Math.min(.2,acc+dt*speedRef.current);while(acc>=1/60&&runRef.current){acc-=1/60;let up=(keys.current.has('w')||keys.current.has('arrowup')?1:0)-(keys.current.has('s')||keys.current.has('arrowdown')?1:0)+stick.current.y;let right=(keys.current.has('d')||keys.current.has('arrowright')?1:0)-(keys.current.has('a')||keys.current.has('arrowleft')?1:0)+stick.current.x;const tactical=cameraRef.current!=='broadcast';frameRef.current=stepTeamGame(frameRef.current,{moveX:tactical?(axesRef.current==='horizontal'?right:up):up*.8455+right*.534,moveY:tactical?(axesRef.current==='horizontal'?-up:right):right*.8455-up*.534,action:action.current},1/60);action.current=null;if(frameRef.current.outcome)stop();}timeRef.current=frameRef.current.time;}
      else{timeRef.current=Math.min(draftRef.current.duration,timeRef.current+dt*speedRef.current);frameRef.current=sampleDraft(draftRef.current,timeRef.current);if(timeRef.current>=draftRef.current.duration)stop();}
      if(now-painted>70||!runRef.current){setTime(timeRef.current);setFrame(frameRef.current);painted=now;}
    }
    const down=e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' ','p','tab'].includes(k)&&liveRef.current){e.preventDefault();keys.current.add(k);if(!e.repeat&&[' ','p','tab'].includes(k))action.current=k===' '?'shoot':k==='p'?'pass':'switch';}if(k==='escape')stop();};
    const up=e=>keys.current.delete(e.key.toLowerCase()),hide=()=>{if(document.hidden)stop()};
    window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',stop);document.addEventListener('visibilitychange',hide);id=requestAnimationFrame(tick);
    return()=>{cancelAnimationFrame(id);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',stop);document.removeEventListener('visibilitychange',hide)};
  },[stop]);
  useEffect(()=>{let records=[];try{const s=JSON.parse(readPracticeValue(localStorage, 'rinkreads_director_library_v1', playerId));if(Array.isArray(s))records=s.filter(item=>Number.isFinite(item?.id)&&validateDraft(item?.draft).ok).slice(0,20);}catch{/* optional local drafts */}setSaved(records);},[saveKey,playerId]);
  const actor=draft.actors.find(a=>a.id===selected),pose=frame.actors.find(a=>a.id===selected);
  function place({x,y},id=selected){edit(d=>{const a=d.actors.find(p=>p.id===id);if(!a)return d;const p=sampleDraft(d,timeRef.current).actors.find(p=>p.id===id);let next=a.frozen?setFrozen(d,id,false,timeRef.current):d;next=putKey(next,id,timeRef.current,{x,y,facing:p.facing});return a.frozen?setFrozen(next,id,true,timeRef.current):next;});}
  function playTimeline(){if(liveRef.current){liveRef.current=false;setLive(false);show(0);}if(timeRef.current>=draft.duration)show(0);runRef.current=true;setRunning(true);}
  function playLive(){stop();try{frameRef.current=createTeamGame(draftRef.current);setFrame(frameRef.current);liveRef.current=true;setLive(true);timeRef.current=0;setTime(0);runRef.current=true;setRunning(true);}catch(e){setNotice(e.message)}}
  function save(){try{assertDraft(draft);const next=[{id:Date.now(),draft:structuredClone(draft)},...saved].slice(0,20);localStorage.setItem(saveKey,JSON.stringify(next));setSaved(next);setNotice('Coach draft saved on this device.');}catch(e){setNotice(`Could not save: ${e.message}`)}}
  async function importFile(e){const input=e.target;try{const file=input.files[0];if(!file)return;if(file.size>1000000)throw new Error('Draft must be smaller than 1 MB.');const value=JSON.parse(await file.text());assertDraft(value);replace(value);setNotice('Draft imported.');}catch(err){setNotice(err.message)}finally{input.value=''}}
  return <section className="pf-director">
    <div className="pf-section-title"><div><p className="oo-eyebrow">COACH LAB / BUILD THE MOMENT</p><h1>Your ice.<br/><em>Your possibilities.</em></h1></div><div className="pf-director-intro">Add the players. Set the space.<br/>Move through time and make the play.</div></div>
    <div className="pf-director-layout"><div className="pf-director-rink">
      <div className="oo-rink-toolbar"><span>{live?'LIVE PRACTICE':running?'PLAYING YOUR TIMELINE':'DIRECTOR / PAUSED'}</span><span>{draft.actors.filter(a=>a.role!=='goalie'&&a.team==='home').length} v {draft.actors.filter(a=>a.role!=='goalie'&&a.team==='away').length}<b>{time.toFixed(1)}s</b></span></div>
      <div className="pf-director-canvas"><PracticeScene frameRef={frameRef} axesRef={axesRef} roster={draft.actors} camera={camera} selectedActor={live?frame.selectedId:selected} onSelect={setSelected} onPlace={!running&&!live?place:undefined}/><div className="oo-camera-controls"><button onClick={()=>{const c=camera==='full'?'broadcast':'full';setCamera(c);cameraRef.current=c}}>{camera==='full'?'Rink camera':'Whole rink'}</button></div><div className="pf-rink-caption">{live?'WASD / arrows · Space shoots · P passes · Tab changes player':`Drag a player, or choose one and tap the ice. Editing at ${time.toFixed(1)}s.`}</div>{live&&<div className="pf-live-pad"><div>{[['↑',0,1],['←',-1,0],['↓',0,-1],['→',1,0]].map(([label,x,y])=><button key={label} aria-label={`Skate ${label}`} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);stick.current={x,y}}} onPointerUp={()=>stick.current={x:0,y:0}} onPointerCancel={()=>stick.current={x:0,y:0}} onLostPointerCapture={()=>stick.current={x:0,y:0}}>{label}</button>)}</div><button onClick={()=>action.current='pass'}>Pass</button><button onClick={()=>action.current='shoot'}>Shoot</button><button onClick={()=>action.current='switch'}>Change player</button></div>}</div>
      <div className="oo-transport"><button className="oo-play-button" onClick={running?stop:playTimeline}>{running?'Ⅱ Pause':'▶ Animate play'}</button><div className="oo-timeline"><label htmlFor="pf-director-time">PLAY TIMELINE <span>{time.toFixed(1)} / {draft.duration}s</span></label><input id="pf-director-time" type="range" min="0" max={draft.duration} step=".05" value={Math.min(time,draft.duration)} onChange={e=>{stop();liveRef.current=false;setLive(false);show(Number(e.target.value))}}/></div><select aria-label="Animation speed" value={speed} onChange={e=>{const s=Number(e.target.value);setSpeed(s);speedRef.current=s}}><option value=".25">¼ speed</option><option value=".5">½ speed</option><option value="1">1× speed</option></select><button aria-label="Rewind coach play" onClick={()=>{stop();liveRef.current=false;setLive(false);show(0)}}>↺</button></div>
      <div className="pf-director-help"><b>1</b> Set starting positions at 0s. <b>2</b> Move the timeline forward. <b>3</b> Drag players to their next positions. Press Animate play.</div>
      {frame.outcome&&<p className="pf-earned" role="status">{String(frame.outcome).toUpperCase()} · Reset the practice or edit the setup and try another read.</p>}
      <div className="pf-draft-strip"><input aria-label="Play title" value={draft.title} onChange={e=>edit(d=>({...d,title:e.target.value}))}/><button onClick={save}>Save draft</button>{onCreateQuestion&&<button onClick={()=>{stop();onCreateQuestion(draft)}}>Ask about these starting positions</button>}<button onClick={()=>{try{downloadDraft(draft);setNotice('Draft exported.')}catch(e){setNotice(e.message)}}}>Export</button><label className="pf-import">Import<input type="file" accept="application/json,.json" onChange={importFile}/></label></div>
      {draft.sourceRef&&<p className="pf-source-id">Based on {draft.sourceRef.id}. Positions copied from the source opening; timing and edits are an unvalidated exploration. The original question is unchanged.</p>}
      {!!saved.length&&<label className="pf-saved">REOPEN A SAVED PLAY<select aria-label="Reopen a saved play" value="" onChange={e=>{try{replace(saved.find(s=>String(s.id)===e.target.value).draft);setNotice('Saved draft reopened.')}catch(err){setNotice(err.message)}}}><option value="">Choose a saved draft…</option>{saved.map(s=><option key={s.id} value={s.id}>{s.draft.title} · {new Date(s.id).toLocaleTimeString()}</option>)}</select></label>}
      {notice&&<p className="oo-notice" role="status">{notice}</p>}
    </div><aside className="pf-roster-panel">
      <p className="oo-eyebrow">START WITH A TEMPLATE</p><div className="pf-templates">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>replace(createDraft(n,n))}>{n}v{n}</button>)}</div>
      <div className="pf-add-row"><button onClick={()=>edit(d=>addActor(d,'home'))}>+ Teammate</button><button onClick={()=>edit(d=>addActor(d,'away'))}>+ Opponent</button></div>
      <div className="pf-add-row"><button onClick={()=>edit(d=>addActor(d,'home','goalie'))}>+ Home goalie</button><button onClick={()=>edit(d=>addActor(d,'away','goalie'))}>+ Away goalie</button></div>
      <div className="pf-roster">{draft.actors.map(a=><button key={a.id} aria-pressed={a.id===selected} className={`${a.team} ${a.id===selected?'selected':''}`} onClick={()=>setSelected(a.id)}><b>{a.label}</b><span>{a.team==='home'?'Teammate':'Opponent'}<small>{a.role==='goalie'?'Goalie':`${a.keys.length} position keys`}</small></span>{a.frozen&&<em>Frozen</em>}</button>)}</div>
      {actor&&pose&&<div className="pf-player-controls"><div className="pf-player-heading"><strong>{actor.label} · Player controls</strong><button aria-label="Remove selected player" onClick={()=>{try{const next=removeActor(draftRef.current,selected);replace(next)}catch(e){setNotice(e.message)}}}>Remove</button></div><button className={actor.frozen?'oo-primary':'oo-secondary'} onClick={()=>edit(d=>setFrozen(d,selected,!actor.frozen,timeRef.current))}>{actor.frozen?'❄ Frozen — unfreeze player':'Freeze this player'}</button><div className="pf-coordinates"><label>LENGTH (m)<input aria-label="Player length position" type="number" step=".25" value={Number(pose.x.toFixed(2))} onChange={e=>place({x:Number(e.target.value),y:pose.y})}/></label><label>WIDTH (m)<input aria-label="Player width position" type="number" step=".25" value={Number(pose.y.toFixed(2))} onChange={e=>place({x:pose.x,y:Number(e.target.value)})}/></label></div><label>FACING · {Math.round(pose.facing*180/Math.PI)}°<input aria-label="Player facing" type="range" min="-180" max="180" value={pose.facing*180/Math.PI} onChange={e=>edit(d=>{let n=actor.frozen?setFrozen(d,selected,false,timeRef.current):d;n=putKey(n,selected,timeRef.current,{x:pose.x,y:pose.y,facing:Number(e.target.value)*Math.PI/180});return actor.frozen?setFrozen(n,selected,true,timeRef.current):n})}/></label><p className="oo-eyebrow">POSITION KEYS</p><div className="pf-keys">{actor.keys.map(k=><button key={k.time} onClick={()=>{stop();liveRef.current=false;setLive(false);show(k.time)}}>{k.time.toFixed(1)}s</button>)}</div><button className="oo-secondary" onClick={()=>{stop();liveRef.current=false;setLive(false);show(Math.min(draft.duration,timeRef.current+2))}}>Next movement beat +2s</button></div>}
      <label className="pf-puck-owner">GIVE THE PUCK TO<select aria-label="Puck carrier" value={draft.puck.owner||''} onChange={e=>edit(d=>({...d,puck:{...d.puck,owner:e.target.value||null}}))}><option value="">Loose puck</option>{draft.actors.filter(a=>a.role!=='goalie').map(a=><option key={a.id} value={a.id}>{a.label} · {a.team}</option>)}</select></label>
      <button className="oo-primary" onClick={playLive}>Play this setup →</button><p className="pf-small">Live practice uses prototype support and opponent movement. Freeze locks still apply.</p>
    </aside></div>
  </section>;
}
