import {useMemo,useState} from 'react';
import {buildCurriculumPracticeInsights} from './curriculumPracticeInsights.js';
import bindings from './experimentalCurriculumBindings.json';
import ledger from '../data/curriculum-ledger.json';

export default function CurriculumPracticePanel({bank,manifest,snapshot}){
 const [age,setAge]=useState(''),[type,setType]=useState('');
 const report=useMemo(()=>buildCurriculumPracticeInsights({bank,manifest,snapshot,bindings,ledger,age,type}),[bank,manifest,snapshot,age,type]);
 const exportReport=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='rinkreads-curriculum-feedback.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="epi-curriculum" aria-labelledby="epi-curriculum-title"><h3 id="epi-curriculum-title">Curriculum coverage and question feedback</h3><p>Current-version activity, connected to explicit scene-level concept mappings. A mapped scene is not proof that every question assesses that concept.</p><div className="epi-actions"><label>Coverage age<select value={age} onChange={e=>setAge(e.target.value)}><option value="">All ages</option>{['U7','U9','U11','U13','U15','U18'].map(a=><option key={a}>{a}</option>)}</select></label><label>Coverage question type<select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{['choice','multi','sequence','position','explain'].map(t=><option key={t}>{t}</option>)}</select></label><button onClick={exportReport}>Export curriculum feedback</button><a href="/docs/factory/curriculum-map/index.html" target="_blank" rel="noreferrer">Full curriculum map ↗</a><a href="/docs/factory/calibration/index.html" target="_blank" rel="noreferrer">Review calibration drafts ↗</a></div>
 <p>{report.authoredScenes} scenes · {report.authoredQuestions} authored questions · {report.currentEvents} current events. {report.staleEvents} historical or unmatched events excluded; {report.duplicateEvents} duplicate events ignored.</p>
 <div className="epi-table-wrap"><table><caption>Provisional concept coverage and this browser’s activity</caption><thead><tr>{['Concept','Scenes','Questions','Views','Checks','Flags','Retries','Scene match'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{report.concepts.map(c=><tr key={c.conceptId}><th scope="row">{c.name}</th><td>{c.scenes}</td><td>{c.authoredQuestions}</td><td>{c.views}</td><td>{c.checks}</td><td>{c.flags}</td><td>{c.retries}</td><td>{c.sceneMatchRate===null?`Not enough data (${c.sceneChecks}/5)`:`${Math.round(c.sceneMatchRate*100)}% (${c.sceneMatches}/${c.sceneChecks})`}</td></tr>)}</tbody></table></div>
 <h3>Questions to inspect next</h3>{report.priorities.length?<ul className="epi-plain">{report.priorities.slice(0,12).map(q=><li key={q.questionId}><a href={q.url}>{q.questionId} · {q.title}</a><br/>{q.reason}: {q.flags} flags · {q.retries} retries · {q.checks} checks</li>)}</ul>:<p>No current-version flags or retry signals yet. This does not establish question quality.</p>}
 {report.unmappedScenes.length>0&&<details><summary>{report.unmappedScenes.length} scenes need a curriculum binding</summary><ul>{report.unmappedScenes.map(s=><li key={s.scenarioId}>{s.scenarioId}: {s.reason}</li>)}</ul></details>}
 <p className="epi-footnote">Local data only. Five scene checks is a display threshold, not statistical confidence. Coaching choices and reflection skips are never graded as wrong here. Counts can overlap across concepts; no mastery or player ranking is inferred. Use Refresh report above after more practice.</p></section>;
}
