// Adapted without content changes from the owner-reviewed prototype; human hockey review pending.
import data from './foundationContent.json';
const {profile:P,roles,spots}=data;const B=data.lines.blue[1],G=data.lines.goal[1];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function foundationRink({mode='landmarks',spot='blue',role='C',phase='attack',turnover='lose'}={}){
function areas(){let side=role==='LW'||role==='LD'?-1:1;let ps=phase==='transition'?(turnover==='win'?'win':'lose'):phase;
if(role==='G')return [[-G+1,0,2.7,3.1,1],[-G+2,0,4,5,.4]];
if(role==='C')return ({attack:[[19,0,9,5,1],[7,0,10,7,.4]],defend:[[-21,0,7,5,1],[-12,0,8,8,.45]],win:[[-5,0,15,6,1],[10,0,9,8,.45]],lose:[[-9,0,14,6,1],[-21,0,7,5,.55]]})[ps];
if(role==='LW'||role==='RW')return ({attack:[[20,side*8,8,5,1],[23,side*2,6,4,.65],[6,side*7,10,4,.3]],defend:[[-12,side*7,7,5,1],[-19,side*3,8,5,.45]],win:[[-6,side*8,14,4,1],[12,side*5,10,5,.55]],lose:[[0,side*5,15,5,1],[-14,side*3,9,5,.6]]})[ps];
return ({attack:[[11,side*7,5,5,1],[4,side*3,9,6,.45]],defend:[[-23,side*4,6,5,1],[-27,0,3,5,.6],[-16,side*9,5,4,.4]],win:[[-19,side*6,9,5,1],[-5,side*4,10,5,.4]],lose:[[-8,side*4,13,5,1],[-23,side*3,7,5,.6]]})[ps];}
const X=x=>350+x*9.7,Y=y=>190+y*9.7;
function base(){let s=`<svg viewBox="0 0 700 380" role="group" aria-label="Rink tour. Our team defends left and attacks right. Select labels below for the same information."><defs><clipPath id="tour-clip"><rect x="${X(P.bounds.minX)}" y="${Y(P.bounds.minY)}" width="${P.lengthM*9.7}" height="${P.widthM*9.7}" rx="65"/></clipPath><radialGradient id="tour-heat"><stop offset="0" stop-color="#d96524" stop-opacity=".82"/><stop offset=".35" stop-color="#f0bc45" stop-opacity=".66"/><stop offset=".7" stop-color="#61bdc4" stop-opacity=".38"/><stop offset="1" stop-color="#6ac2ce" stop-opacity="0"/></radialGradient></defs><rect x="${X(P.bounds.minX)}" y="${Y(P.bounds.minY)}" width="${P.lengthM*9.7}" height="${P.widthM*9.7}" rx="65" fill="#f7fcff" stroke="#59758b" stroke-width="3"/>`;
if(mode==='heat')s+=`<g clip-path="url(#tour-clip)">${areas().map(([x,y,rx,ry,o])=>`<ellipse data-heat-area="" cx="${X(x)}" cy="${Y(y)}" rx="${rx*9.7}" ry="${ry*9.7}" opacity="${o}" fill="url(#tour-heat)"/>`).join('')}</g>`;
if(mode==='landmarks'){const q=spots.find(a=>a[0]===spot);let rectangles={dz:[-30.48,-12.954,30.48-B,25.908],nz:[-B,-12.954,B*2,25.908],oz:[B,-12.954,30.48-B,25.908]};if(rectangles[spot]){const [x,y,w,h]=rectangles[spot];s+=`<rect x="${X(x)}" y="${Y(y)}" width="${w*9.7}" height="${h*9.7}" fill="#e8b641" opacity=".22" clip-path="url(#tour-clip)"/>`;}if(q[2]==='tactical'&&!['hash','benches','official'].includes(spot)){let radius={slot:[6,4],highslot:[4,5],points:[3,3],halfwall:[5,2],corners:[3,3],behind:[1.5,4],netfront:[2,3]}[spot];if(radius)s+=`<ellipse cx="${X(q[3])}" cy="${Y(q[4])}" rx="${radius[0]*9.7}" ry="${radius[1]*9.7}" fill="#e8b641" opacity=".32" stroke="#99721d" stroke-dasharray="5 5" clip-path="url(#tour-clip)"/>`;}}
if(mode==='landmarks'){
 const xs=spot==='blue'?[-B,B]:spot==='centre'?[0]:spot==='goal'?[-G,G]:[];
 for(const x of xs)s+=`<path d="M${X(x)} ${Y(-13)}V${Y(13)}" stroke="#e8b641" stroke-width="17" opacity=".32" clip-path="url(#tour-clip)"/>`;
 if(spot==='circles')for(const [x,y]of data.lines.circles)s+=`<circle cx="${X(x)}" cy="${Y(y)}" r="44.35" fill="#e8b641" opacity=".24"/>`;
 if(spot==='boards')s+=`<rect x="${X(P.bounds.minX)}" y="${Y(P.bounds.minY)}" width="${P.lengthM*9.7}" height="${P.widthM*9.7}" rx="65" fill="none" stroke="#c99325" stroke-width="8" opacity=".65"/>`;
}
s+='<g clip-path="url(#tour-clip)" opacity=".8">';for(const x of [-B,B])s+=`<path d="M${X(x)} ${Y(-13)}V${Y(13)}" stroke="#3578b5" stroke-width="4"/>`;for(const x of [-G,0,G])s+=`<path d="M${X(x)} ${Y(-13)}V${Y(13)}" stroke="#c4585e" stroke-width="${x===0?2:1.5}"/>`;for(const [x,y]of [[0,0],...data.lines.circles])s+=`<circle cx="${X(x)}" cy="${Y(y)}" r="44.35" fill="none" stroke="${x===0?'#3578b5':'#b4676d'}" stroke-width="1.5"/><circle cx="${X(x)}" cy="${Y(y)}" r="3" fill="#ac4f59"/>`;for(const x of [-6.2,6.2])for(const y of [-6.25,6.25])s+=`<circle cx="${X(x)}" cy="${Y(y)}" r="3" fill="#ac4f59"/>`;for(const x of [-G,G]){const dir=x<0?1:-1;s+=`<path d="M${X(x)} ${Y(-1.83)} Q${X(x+dir*3.4)} ${Y(0)} ${X(x)} ${Y(1.83)}Z" fill="#c3e5f0" stroke="#bb656a"/>`;}
s+='</g>';for(const x of [-G,G])s+=`<rect x="${X(x)+(x>0?0:-12)}" y="${Y(-.9144)}" width="12" height="18" fill="#dce5eb" stroke="#ac454f" stroke-width="2"/>`;
for(const c of data.lines.circles)for(const dy of [-4.5,4.5])s+=`<path d="M${X(c[0]-.4)} ${Y(c[1]+dy)}h8" stroke="#aa5c66" stroke-width="2"/>`;
s+=`<rect x="${X(-16)}" y="28" width="125" height="16" rx="3" fill="#dce7ee"/><rect x="${X(3)}" y="28" width="125" height="16" rx="3" fill="#dce7ee"/><path d="M${X(-3)} ${Y(12.95)}Q350 ${Y(8)} ${X(3)} ${Y(12.95)}" fill="none" stroke="#b4676d" stroke-width="1.5"/>`;
if(mode==='landmarks'){const q=spots.find(a=>a[0]===spot),shown=spots.filter(a=>a[0]===spot);s+=shown.map(a=>{const n=spots.indexOf(a)+1;return `<g role="button" tabindex="0" data-spot="${a[0]}" aria-label="${n}. ${esc(a[1])}" aria-pressed="${a[0]===spot}"><circle cx="${X(a[3])}" cy="${Y(a[4])}" r="19" fill="transparent"/><circle cx="${X(a[3])}" cy="${Y(a[4])}" r="${a[0]===spot?19:16}" fill="${a[0]===spot?'#bd851b':'#173450'}" stroke="white" stroke-width="2"/><text class="spot-num" x="${X(a[3])}" y="${Y(a[4])}" fill="white" text-anchor="middle" font-family="system-ui" font-size="15" font-weight="700">${n}</text></g>`;}).join('');}
if(mode==='lineup'){s+=Object.entries(roles).map(([id,r])=>`<g role="button" tabindex="0" data-role="${id}" aria-label="${esc(r.name)}" aria-pressed="${role===id}"><circle cx="${X(r.x)}" cy="${Y(r.y)}" r="24" fill="transparent"/><circle cx="${X(r.x)}" cy="${Y(r.y)}" r="24" fill="${role===id?'#bd851b':'#173450'}" stroke="white" stroke-width="2"/><text class="role-label" x="${X(r.x)}" y="${Y(r.y)}" text-anchor="middle" fill="white" font-family="system-ui" font-size="17" font-weight="700">${id}</text></g>`).join('');s+=`<circle cx="350" cy="190" r="4" fill="#172b42"/>`;}
return s+'</svg>';}

return base();
}
