import {useEffect,useMemo,useState} from 'react';
import {evaluatePlacement,placementSource} from './placementEvaluation.js';
import pack from '../../docs/factory/coaching-panel/placement-pilot.json';
export default function PlacementFeedback({scenario,question,scene,point,onTry,onExample,onNext,showAreas,onToggleAreas,hasAreas}){
 const [attempts,setAttempts]=useState([]);
 const rubric=import.meta.env.DEV?pack.rubrics.find(r=>r.questionId===question.id):null;
 const result=useMemo(()=>evaluatePlacement({scene,point,rubric,questionId:question.id,scenarioVersion:scenario.version,sourceSignature:placementSource(scenario,question)}),[scene,point,rubric,scenario,question]);
 useEffect(()=>{if(!result.previewBand){setAttempts([]);return;}try{const key='rr-placement-preview-events',raw=JSON.parse(localStorage.getItem(key)||'[]'),rows=Array.isArray(raw)?raw:[];const event={questionId:question.id,contentHash:rubric.contentHash,rubricHash:rubric.rubricHash,point,band:result.previewBand,criteria:result.criteria,masteryEligible:false};const serial=JSON.stringify(event);if(rows.at(-1)?.signature!==serial){rows.push({at:new Date().toISOString(),signature:serial,...event});localStorage.setItem(key,JSON.stringify(rows.slice(-300)))}setAttempts(rows.filter(r=>r.questionId===question.id&&r.contentHash===rubric.contentHash&&r.rubricHash===rubric.rubricHash&&r.point&&Number.isFinite(r.point.x)&&Number.isFinite(r.point.y)));}catch{setAttempts([])}},[result,point,question.id,rubric]);
 return <section aria-label="Placement feedback" className="rr-feedback"><strong>{result.previewBand?{strong:'Draft check: strong geometry',workable:'Draft check: workable with a tradeoff',adjust:'Draft check: try adjusting'}[result.previewBand]:'Placement needs judgment'}</strong>
 {result.previewBand?<><ul>{result.criteria.slice(0,3).map(c=><li key={c.id}><b>{c.band==='strong'?'Works':c.band==='workable'?'Tradeoff':'Adjust'}:</b> {c.reason}</li>)}</ul><small>Experimental geometry ranges. They do not predict a completed pass or award mastery.</small></>:<p>{result.reason} Compare the passing lane, spacing and pressure with the example.</p>}
 {hasAreas&&result.previewBand&&<p><button type="button" aria-pressed={showAreas} onClick={onToggleAreas}>{showAreas?'Hide':'Show'} draft areas</button>{showAreas&&<small> Green: strong geometry. Gold: workable range. These approximate shaded cells use the same checks in both views; unshaded spots may need judgment.</small>}</p>}
 {attempts.length>1&&<div aria-label="Attempt comparison"><strong>Compare your attempts</strong><p>First saved: {attempts[0].band} ({attempts[0].point.x}, {attempts[0].point.y} m). Latest: {attempts.at(-1).band} ({attempts.at(-1).point.x}, {attempts.at(-1).point.y} m).</p><small>For this question and rubric version, in this browser. Up to 300 recent checks are retained.</small></div>}
 <p><button type="button" onClick={onTry}>Try another spot</button>{onNext&&<button type="button" onClick={onNext}>Next question →</button>}</p><details><summary>Compare the example</summary><p>{question.explanation}</p><button type="button" onClick={onExample}>Show example on overhead board</button></details></section>;
}
