import {useEffect,useRef,useState} from 'react';
import {pilotHomeModel} from './pilotHomeCore.js';
import {STAGES} from '../one-on-one/foundationFlowCore.js';
import './PilotHome.css';
import WelcomeTour from './WelcomeTour.jsx';
import {PILOT_TOUR_STEPS} from './welcomeTourCore.js';
function storage(){try{return globalThis.localStorage;}catch{return null;}}
export default function PilotHome({playerId,ageBand,onStart,onAgeChange,onParentNavigate,publicPreview=false}){
  const [,refresh]=useState(0);
  const parentsRef=useRef(null),pathRef=useRef(null);
  function openSection(id){if(id==='start'||id==='pictures'){onStart(id==='pictures'?0:undefined);return;}const target=id==='parents'?parentsRef.current:pathRef.current;if(!target)return;if(id==='parents')target.open=true;target.scrollIntoView({behavior:'instant',block:'start'});(target.querySelector('summary')||target.querySelector('h2'))?.focus({preventScroll:true});}
  const tourSteps=PILOT_TOUR_STEPS.map((step,i)=>({...step,action:['start','path','pictures','parents'][i],...(i===3&&publicPreview?{body:'Open For parents for help with the demo, choosing sections, saved progress and adult support. This preview has no account or payment. You can return to this walkthrough with Show me around.'}:{})}));
  useEffect(()=>{const update=()=>refresh(n=>n+1);window.addEventListener('storage',update);window.addEventListener('focus',update);return()=>{window.removeEventListener('storage',update);window.removeEventListener('focus',update);};},[]);
  const model=pilotHomeModel({playerId,ageBand,storage:storage()});
  if(!model.supported)return null;
  return <section className="ph-root" aria-label="Pilot player home">
    <header className="ph-header"><strong>RinkReads<span>.</span></strong><span>{model.age} · Player pilot</span></header>
    <p className="ph-review">{publicPreview?'Early preview · human content review pending':'Local pilot preview · human content review pending'}</p>
    <WelcomeTour playerId={playerId} variant="pilot" steps={tourSteps} onAction={publicPreview?openSection:undefined}/>
    <div className="ph-hero"><div className="ph-world-art" role="img" aria-label="Frozen Trails: a winding ice path through a snowy forest toward a warmly lit cabin."/><div className="ph-intro"><p className="ph-kicker">FROZEN TRAILS · YOUR FIRST HOCKEY WORLD</p><h1>{model.completed?'Look what you explored.':model.started?'Ready to keep going?':'Your next step starts here.'}</h1><p>Learn the rink, meet the positions and get ready to play. One small activity at a time.</p></div>
      <article className="ph-next"><p>{model.completed?'YOUR RECAP':model.started?'PICK UP HERE':'FIRST UP'}</p><h2>{model.next}</h2><button data-pilot-start onClick={()=>onStart()}>{model.label}<span aria-hidden="true"> →</span></button><p className="ph-save" role="status">{model.available?'Your place is saved on this device, separately for each player and age.':'Device storage is unavailable. You can practice, but your place may be lost when you leave.'}</p></article>
    </div>
    <section ref={pathRef} className="ph-path" aria-label="Your foundation path"><h2 tabIndex={-1}>A little at a time.</h2>{publicPreview&&<p>We recommend exploring these sections in order, but you can jump to any section for this demo.</p>}<ol>{STAGES.map((name,i)=><li key={name} aria-current={i===model.stage?'step':undefined}><span aria-hidden="true">{model.explored[i]?'✓':i+1}</span><div>{publicPreview?<button onClick={()=>onStart(i)}>{name}</button>:name}<small>{model.explored[i]?'Explored':i===model.stage?'You are here':publicPreview?'Available to explore':'Coming next'}</small></div></li>)}</ol><p>Exploring an activity is a starting point. Keep asking questions and practicing on the ice.</p></section>
    <details ref={parentsRef} className="ph-parents"><summary>For parents</summary>{publicPreview&&<div className="ph-help"><h3>Try the demo together</h3><p>Choose any section from the learning path. Skip for now moves ahead without completing an activity. Tap a rink feature or player to explore it; use the labelled controls if that is easier.</p><h3>Where is our progress?</h3><p>Progress is kept in this browser for the selected age group. Re-enter the code on this device and choose the same age. Another browser or device will not have it. Clearing browser data removes it. In this public demo, children using the same age and browser share the sample progress.</p><h3>Need a simpler view?</h3><p>Choose 2D rink if 3D is unavailable. View controls and labelled buttons work without dragging. An adult can read the prompts aloud and help with gear and rules questions.</p><div className="ph-help-actions"><button onClick={()=>onStart(0)}>Open Know the ice</button><button onClick={()=>onStart(5)}>Open demo recap</button></div></div>}<p>U7 players may need an adult to read and explore with them. This review flow records activity completion; it does not certify equipment fit, hockey ability or mastery.</p><p>Progress is device-local. Use the same browser to return. This pilot preview does not change your account or plan.</p>{onAgeChange&&<label>Review age group <select aria-label="Pilot age group" value={model.age} onChange={e=>onAgeChange(e.target.value)}>{['U7','U9','U11'].map(age=><option key={age}>{age}</option>)}</select></label>}{onParentNavigate&&<nav aria-label="Parent options">{[['profile','Player profile'],['history','Earlier activity'],['worlds','Browse hockey worlds']].map(([id,label])=><button key={id} onClick={()=>onParentNavigate(id)}>{label}</button>)}</nav>}</details>
  </section>;
}
