import test from 'node:test';import assert from 'node:assert/strict';
import {validatePanelReviews} from './coaching-panel-review.mjs';
const manifest={questions:[{questionId:'q',hash:'h',type:'choice',optionIds:['a','b']}]};
const row={questionId:'q',contentHash:'h',verdict:'retain',highRisk:false,sceneEvidence:'Actor A is home and owns the puck.',reason:'Both visible ownership and roster support a.',optionReviews:[{optionId:'a',assessment:'supported',reason:'A owns puck.'},{optionId:'b',assessment:'unsupported',reason:'B does not own puck.'}]};
test('complete option-specific review passes structural checks only',()=>{assert.deepEqual(validatePanelReviews(manifest,{reviewer:'one',rows:[row]}).errors,[]);});
test('stale hash and missing or duplicate options cannot pass',()=>{for(const change of [{contentHash:'old'},{optionReviews:[row.optionReviews[0]]},{optionReviews:[row.optionReviews[0],row.optionReviews[0]]}])assert(validatePanelReviews(manifest,{reviewer:'one',rows:[{...row,...change}]}).errors.length);});
test('all flags and mandatory high-risk formats need independent review',()=>{for(const change of [{verdict:'repair'},{highRisk:true}])assert(validatePanelReviews(manifest,{reviewer:'one',rows:[{...row,...change}]}).errors.some(e=>e.includes('second review')));const m={questions:[{...manifest.questions[0],type:'position'}]};assert(validatePanelReviews(m,{reviewer:'one',rows:[row]}).errors.length);});
test('same reviewer cannot stand in for independent check and missing rows remain open',()=>{const lead={reviewer:'one',rows:[{...row,highRisk:true}]};assert(validatePanelReviews(manifest,lead,{reviewer:'one',rows:[row]}).errors.length);assert.equal(validatePanelReviews(manifest,lead,{reviewer:'two',rows:[row]}).errors.length,0);assert(validatePanelReviews(manifest,{reviewer:'one',rows:[]}).errors.length);});
test('empty, duplicate or hashless manifests cannot certify an empty or ambiguous packet',()=>{for(const m of [{questions:[]},{questions:[manifest.questions[0],manifest.questions[0]]},{questions:[{...manifest.questions[0],hash:''}]}])assert(validatePanelReviews(m,{reviewer:'one',rows:[row]}).errors.some(e=>e.includes('manifest')));});
